# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tin Nguyen
email: tindn14@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My thoughts shared with the world.
url: 'http://tindn.github.io' # the base hostname & protocol for your site
twitter_username: tindn
github_username: tindn

# Build settings
markdown: kramdown
kramdown:
  input: GFM
